import { gql, useQuery } from '@apollo/client';
import type { GetServerSideProps, NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { withApollo } from '../withApollo';
import {
  PageGetBooksComp,
  ssrGetBooks,
  ssrHome,
  useGetBooks,
} from '../src/generated/page';
import styles from '../styles/Home.module.css';
import { useLoginMutation } from '../src/generated/graphql';

const Home: PageGetBooksComp = (props) => {
  const [login] = useLoginMutation();
  console.log(props);

  const handleLogin = async () => {
    const { data } = await login({
      variables: { email: 'hi@hi.com', password: 'securepassword' },
    });
    if (data?.login?.token) {
      localStorage.setItem('token', data.login.token);
    }
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {props.data?.books?.map((book) => (
        <div key={book?.title}>{book?.title}</div>
      ))}
      <button onClick={handleLogin}>Login</button>

      <main className={styles.main}>
        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export const getStaticProps: GetServerSideProps = async (ctx) => {
  const res = await ssrHome.getServerPage(
    { variables: { title: 'The Conjuring' } },
    ctx
  );
  console.log(res.props.data);
  return res;
};

export default withApollo(
  ssrHome.withPage(() => ({ variables: { title: 'The Conjuring' } }))(Home)
);
